// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy6Ror_47Y4fSzkqx858p7C-dgRkQxFns',
    appId: '1:487139610476:web:b0391bd1c8e0b966a9ed49',
    messagingSenderId: '487139610476',
    projectId: 'pushnotification-b2f2a',
    authDomain: 'pushnotification-b2f2a.firebaseapp.com',
    storageBucket: 'pushnotification-b2f2a.appspot.com',
    measurementId: 'G-RWMEFJN0TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MJOrxbwXiEeT4LD_pI2-JILlrSJ5ZX4',
    appId: '1:487139610476:android:12707852c4ad2e04a9ed49',
    messagingSenderId: '487139610476',
    projectId: 'pushnotification-b2f2a',
    storageBucket: 'pushnotification-b2f2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsNTPJRpRwNmlM9BKExKqnpUJ80Od8zzM',
    appId: '1:487139610476:ios:51bfe3187c0ceb7da9ed49',
    messagingSenderId: '487139610476',
    projectId: 'pushnotification-b2f2a',
    storageBucket: 'pushnotification-b2f2a.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsNTPJRpRwNmlM9BKExKqnpUJ80Od8zzM',
    appId: '1:487139610476:ios:51bfe3187c0ceb7da9ed49',
    messagingSenderId: '487139610476',
    projectId: 'pushnotification-b2f2a',
    storageBucket: 'pushnotification-b2f2a.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy6Ror_47Y4fSzkqx858p7C-dgRkQxFns',
    appId: '1:487139610476:web:36af3fe96ef8bfa3a9ed49',
    messagingSenderId: '487139610476',
    projectId: 'pushnotification-b2f2a',
    authDomain: 'pushnotification-b2f2a.firebaseapp.com',
    storageBucket: 'pushnotification-b2f2a.appspot.com',
    measurementId: 'G-KMRCZE616B',
  );
}
